
// This file has been generated by the GUI designer. Do not modify.
namespace EscuelaPrimaria
{
	public partial class Principal
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EscuelaPrimaria.Principal
			this.Name = "EscuelaPrimaria.Principal";
			this.Title = global::Mono.Unix.Catalog.GetString ("Principal");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
