
// This file has been generated by the GUI designer. Do not modify.
namespace EscuelaPrimaria
{
	public partial class Cordinacion
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EscuelaPrimaria.Cordinacion
			this.Name = "EscuelaPrimaria.Cordinacion";
			this.Title = global::Mono.Unix.Catalog.GetString ("Cordimacion");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
