
// This file has been generated by the GUI designer. Do not modify.
namespace EscuelaPrimaria
{
	public partial class Alumnos
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Notebook notebook2;
		private global::Gtk.Fixed fixed5;
		private global::Gtk.Entry telEmTxt;
		private global::Gtk.Entry aviTxt;
		private global::Gtk.Entry telTxt;
		private global::Gtk.Entry colTxt;
		private global::Gtk.Entry numIntTex;
		private global::Gtk.Entry numExtTxt;
		private global::Gtk.Entry calleTxt;
		private global::Gtk.Entry maternoTxt;
		private global::Gtk.Entry paternoTxt;
		private global::Gtk.Entry nomTxt;
		private global::Gtk.Entry codTxt;
		private global::Gtk.Label label11;
		private global::Gtk.Label label12;
		private global::Gtk.Label label13;
		private global::Gtk.Label label14;
		private global::Gtk.Label label15;
		private global::Gtk.Label label16;
		private global::Gtk.Label label17;
		private global::Gtk.Label label18;
		private global::Gtk.Label label19;
		private global::Gtk.Label label20;
		private global::Gtk.Label label9;
		private global::Gtk.Label label10;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Label label7;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EscuelaPrimaria.Alumnos
			this.Name = "EscuelaPrimaria.Alumnos";
			this.Title = global::Mono.Unix.Catalog.GetString ("Alumnos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child EscuelaPrimaria.Alumnos.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.HeightRequest = 66;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.vbox1.Add (this.fixed2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 0;
			this.notebook2.Scrollable = true;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.telEmTxt = new global::Gtk.Entry ();
			this.telEmTxt.CanFocus = true;
			this.telEmTxt.Name = "telEmTxt";
			this.telEmTxt.IsEditable = true;
			this.telEmTxt.InvisibleChar = '●';
			this.fixed5.Add (this.telEmTxt);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.telEmTxt]));
			w2.X = 388;
			w2.Y = 277;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.aviTxt = new global::Gtk.Entry ();
			this.aviTxt.CanFocus = true;
			this.aviTxt.Name = "aviTxt";
			this.aviTxt.IsEditable = true;
			this.aviTxt.InvisibleChar = '●';
			this.fixed5.Add (this.aviTxt);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.aviTxt]));
			w3.X = 387;
			w3.Y = 240;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.telTxt = new global::Gtk.Entry ();
			this.telTxt.CanFocus = true;
			this.telTxt.Name = "telTxt";
			this.telTxt.IsEditable = true;
			this.telTxt.InvisibleChar = '●';
			this.fixed5.Add (this.telTxt);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.telTxt]));
			w4.X = 386;
			w4.Y = 202;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.colTxt = new global::Gtk.Entry ();
			this.colTxt.CanFocus = true;
			this.colTxt.Name = "colTxt";
			this.colTxt.IsEditable = true;
			this.colTxt.InvisibleChar = '●';
			this.fixed5.Add (this.colTxt);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.colTxt]));
			w5.X = 385;
			w5.Y = 163;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.numIntTex = new global::Gtk.Entry ();
			this.numIntTex.CanFocus = true;
			this.numIntTex.Name = "numIntTex";
			this.numIntTex.IsEditable = true;
			this.numIntTex.InvisibleChar = '●';
			this.fixed5.Add (this.numIntTex);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.numIntTex]));
			w6.X = 385;
			w6.Y = 124;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.numExtTxt = new global::Gtk.Entry ();
			this.numExtTxt.CanFocus = true;
			this.numExtTxt.Name = "numExtTxt";
			this.numExtTxt.IsEditable = true;
			this.numExtTxt.InvisibleChar = '●';
			this.fixed5.Add (this.numExtTxt);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.numExtTxt]));
			w7.X = 109;
			w7.Y = 276;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.calleTxt = new global::Gtk.Entry ();
			this.calleTxt.CanFocus = true;
			this.calleTxt.Name = "calleTxt";
			this.calleTxt.IsEditable = true;
			this.calleTxt.InvisibleChar = '●';
			this.fixed5.Add (this.calleTxt);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.calleTxt]));
			w8.X = 108;
			w8.Y = 238;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.maternoTxt = new global::Gtk.Entry ();
			this.maternoTxt.CanFocus = true;
			this.maternoTxt.Name = "maternoTxt";
			this.maternoTxt.IsEditable = true;
			this.maternoTxt.InvisibleChar = '●';
			this.fixed5.Add (this.maternoTxt);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.maternoTxt]));
			w9.X = 109;
			w9.Y = 201;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.paternoTxt = new global::Gtk.Entry ();
			this.paternoTxt.CanFocus = true;
			this.paternoTxt.Name = "paternoTxt";
			this.paternoTxt.IsEditable = true;
			this.paternoTxt.InvisibleChar = '●';
			this.fixed5.Add (this.paternoTxt);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.paternoTxt]));
			w10.X = 109;
			w10.Y = 165;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.nomTxt = new global::Gtk.Entry ();
			this.nomTxt.CanFocus = true;
			this.nomTxt.Name = "nomTxt";
			this.nomTxt.IsEditable = true;
			this.nomTxt.InvisibleChar = '●';
			this.fixed5.Add (this.nomTxt);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.nomTxt]));
			w11.X = 110;
			w11.Y = 129;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.codTxt = new global::Gtk.Entry ();
			this.codTxt.CanFocus = true;
			this.codTxt.Name = "codTxt";
			this.codTxt.IsEditable = true;
			this.codTxt.InvisibleChar = '●';
			this.fixed5.Add (this.codTxt);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.codTxt]));
			w12.X = 109;
			w12.Y = 91;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido Paterno:");
			this.fixed5.Add (this.label11);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label11]));
			w13.X = 7;
			w13.Y = 167;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido Materno:");
			this.fixed5.Add (this.label12);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label12]));
			w14.X = 6;
			w14.Y = 203;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Calle:");
			this.fixed5.Add (this.label13);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label13]));
			w15.X = 68;
			w15.Y = 242;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero:");
			this.fixed5.Add (this.label14);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label14]));
			w16.X = 55;
			w16.Y = 279;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString (" Numero Interior:");
			this.fixed5.Add (this.label15);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label15]));
			w17.X = 283;
			w17.Y = 129;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Colonia:");
			this.fixed5.Add (this.label16);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label16]));
			w18.X = 335;
			w18.Y = 166;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString (" Teléfono:");
			this.fixed5.Add (this.label17);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label17]));
			w19.X = 323;
			w19.Y = 206;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Avisar:");
			this.fixed5.Add (this.label18);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label18]));
			w20.X = 343;
			w20.Y = 242;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Teléfono de");
			this.fixed5.Add (this.label19);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label19]));
			w21.X = 306;
			w21.Y = 273;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Emergencia:");
			this.fixed5.Add (this.label20);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label20]));
			w22.X = 307;
			w22.Y = 290;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Código:");
			this.fixed5.Add (this.label9);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label9]));
			w23.X = 57;
			w23.Y = 98;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.fixed5.Add (this.label10);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label10]));
			w24.X = 53;
			w24.Y = 133;
			this.notebook2.Add (this.fixed5);
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Datos Personales");
			this.notebook2.SetTabLabel (this.fixed5, this.label4);
			this.label4.ShowAll ();
			// Notebook tab
			global::Gtk.Label w26 = new global::Gtk.Label ();
			w26.Visible = true;
			this.notebook2.Add (w26);
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Materias");
			this.notebook2.SetTabLabel (w26, this.label5);
			this.label5.ShowAll ();
			// Notebook tab
			global::Gtk.Label w27 = new global::Gtk.Label ();
			w27.Visible = true;
			this.notebook2.Add (w27);
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Cursos");
			this.notebook2.SetTabLabel (w27, this.label6);
			this.label6.ShowAll ();
			// Notebook tab
			global::Gtk.Label w28 = new global::Gtk.Label ();
			w28.Visible = true;
			this.notebook2.Add (w28);
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Pagos");
			this.notebook2.SetTabLabel (w28, this.label7);
			this.label7.ShowAll ();
			this.vbox1.Add (this.notebook2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook2]));
			w29.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 604;
			this.DefaultHeight = 479;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
