
// This file has been generated by the GUI designer. Do not modify.
namespace EscuelaPrimaria
{
	public partial class Nomina
	{
		private global::Gtk.Fixed fixed5;
		private global::Gtk.Image image1;
		private global::Gtk.Image image2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView nodeview1;
		private global::Gtk.Image image6;
		private global::Gtk.Label idLabel;
		private global::Gtk.Entry idTxt;
		private global::Gtk.Label label9;
		private global::Gtk.Label label4;
		private global::Gtk.Entry codTxt;
		private global::Gtk.Entry nomTxt;
		private global::Gtk.Label label10;
		private global::Gtk.Label label2;
		private global::Gtk.Entry codigoFolio;
		private global::Gtk.Label label3;
		private global::Gtk.Label label6;
		private global::Gtk.Entry dia;
		private global::Gtk.Label label8;
		private global::Gtk.Entry mes;
		private global::Gtk.Label label11;
		private global::Gtk.Entry ano;
		private global::Gtk.Label label12;
		private global::Gtk.Label label7;
		private global::Gtk.Button carger;
		private global::Gtk.Label idCor;
		private global::Gtk.Entry horasTrabajadasTxt;
		private global::Gtk.Label label5;
		private global::Gtk.Entry horasExtraTxt;
		private global::Gtk.Label label13;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView comentario;
		private global::Gtk.Button cancelar;
		private global::Gtk.Button pagar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EscuelaPrimaria.Nomina
			this.Name = "EscuelaPrimaria.Nomina";
			this.Title = global::Mono.Unix.Catalog.GetString ("Nomina");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child EscuelaPrimaria.Nomina.Gtk.Container+ContainerChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.RojoBajito.png");
			this.fixed5.Add (this.image1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.image1]));
			w1.X = 3;
			w1.Y = 3;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.NominaPago.png");
			this.fixed5.Add (this.image2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.image2]));
			w2.X = 7;
			w2.Y = 4;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.TreeView ();
			this.nodeview1.WidthRequest = 251;
			this.nodeview1.HeightRequest = 300;
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.GtkScrolledWindow.Add (this.nodeview1);
			this.fixed5.Add (this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.GtkScrolledWindow]));
			w4.X = 13;
			w4.Y = 101;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.EscuelaPrimaria3.png");
			this.fixed5.Add (this.image6);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.image6]));
			w5.X = 554;
			w5.Y = 4;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.idLabel = new global::Gtk.Label ();
			this.idLabel.Name = "idLabel";
			this.idLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("ID:");
			this.fixed5.Add (this.idLabel);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.idLabel]));
			w6.X = 316;
			w6.Y = 115;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.idTxt = new global::Gtk.Entry ();
			this.idTxt.WidthRequest = 35;
			this.idTxt.CanFocus = true;
			this.idTxt.Name = "idTxt";
			this.idTxt.IsEditable = false;
			this.idTxt.InvisibleChar = '●';
			this.fixed5.Add (this.idTxt);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.idTxt]));
			w7.X = 336;
			w7.Y = 112;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Código Profesor:");
			this.fixed5.Add (this.label9);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label9]));
			w8.X = 376;
			w8.Y = 115;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Datos Del Profesor");
			this.fixed5.Add (this.label4);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label4]));
			w9.X = 425;
			w9.Y = 84;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.codTxt = new global::Gtk.Entry ();
			this.codTxt.CanFocus = true;
			this.codTxt.Name = "codTxt";
			this.codTxt.IsEditable = false;
			this.codTxt.InvisibleChar = '●';
			this.fixed5.Add (this.codTxt);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.codTxt]));
			w10.X = 488;
			w10.Y = 110;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.nomTxt = new global::Gtk.Entry ();
			this.nomTxt.WidthRequest = 251;
			this.nomTxt.CanFocus = true;
			this.nomTxt.Name = "nomTxt";
			this.nomTxt.IsEditable = false;
			this.nomTxt.InvisibleChar = '●';
			this.fixed5.Add (this.nomTxt);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.nomTxt]));
			w11.X = 451;
			w11.Y = 146;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre del Profesor:");
			this.fixed5.Add (this.label10);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label10]));
			w12.X = 313;
			w12.Y = 150;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Datos del Pago");
			this.fixed5.Add (this.label2);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label2]));
			w13.X = 417;
			w13.Y = 185;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.codigoFolio = new global::Gtk.Entry ();
			this.codigoFolio.CanFocus = true;
			this.codigoFolio.Name = "codigoFolio";
			this.codigoFolio.IsEditable = true;
			this.codigoFolio.InvisibleChar = '●';
			this.fixed5.Add (this.codigoFolio);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.codigoFolio]));
			w14.X = 354;
			w14.Y = 213;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Folio:");
			this.fixed5.Add (this.label3);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label3]));
			w15.X = 317;
			w15.Y = 217;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha:");
			this.fixed5.Add (this.label6);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label6]));
			w16.X = 526;
			w16.Y = 217;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.dia = new global::Gtk.Entry ();
			this.dia.WidthRequest = 35;
			this.dia.CanFocus = true;
			this.dia.Name = "dia";
			this.dia.IsEditable = true;
			this.dia.InvisibleChar = '●';
			this.fixed5.Add (this.dia);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.dia]));
			w17.X = 568;
			w17.Y = 212;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Dia");
			this.fixed5.Add (this.label8);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label8]));
			w18.X = 575;
			w18.Y = 195;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.mes = new global::Gtk.Entry ();
			this.mes.WidthRequest = 35;
			this.mes.CanFocus = true;
			this.mes.Name = "mes";
			this.mes.IsEditable = true;
			this.mes.InvisibleChar = '●';
			this.fixed5.Add (this.mes);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.mes]));
			w19.X = 602;
			w19.Y = 212;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("mes");
			this.fixed5.Add (this.label11);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label11]));
			w20.X = 608;
			w20.Y = 194;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.ano = new global::Gtk.Entry ();
			this.ano.WidthRequest = 35;
			this.ano.CanFocus = true;
			this.ano.Name = "ano";
			this.ano.IsEditable = true;
			this.ano.InvisibleChar = '●';
			this.fixed5.Add (this.ano);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.ano]));
			w21.X = 636;
			w21.Y = 213;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("año");
			this.fixed5.Add (this.label12);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label12]));
			w22.X = 643;
			w22.Y = 194;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Monto del pago:");
			this.fixed5.Add (this.label7);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label7]));
			w23.X = 315;
			w23.Y = 261;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.carger = new global::Gtk.Button ();
			this.carger.CanFocus = true;
			this.carger.Name = "carger";
			this.carger.UseUnderline = true;
			this.carger.Label = global::Mono.Unix.Catalog.GetString ("Cargar Maestro");
			this.fixed5.Add (this.carger);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.carger]));
			w24.X = 83;
			w24.Y = 430;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.idCor = new global::Gtk.Label ();
			this.idCor.Name = "idCor";
			this.idCor.LabelProp = global::Mono.Unix.Catalog.GetString ("id");
			this.fixed5.Add (this.idCor);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.idCor]));
			w25.X = 13;
			w25.Y = 421;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.horasTrabajadasTxt = new global::Gtk.Entry ();
			this.horasTrabajadasTxt.WidthRequest = 102;
			this.horasTrabajadasTxt.CanFocus = true;
			this.horasTrabajadasTxt.Name = "horasTrabajadasTxt";
			this.horasTrabajadasTxt.IsEditable = true;
			this.horasTrabajadasTxt.InvisibleChar = '●';
			this.fixed5.Add (this.horasTrabajadasTxt);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.horasTrabajadasTxt]));
			w26.X = 412;
			w26.Y = 256;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Horas Extra:");
			this.fixed5.Add (this.label5);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label5]));
			w27.X = 518;
			w27.Y = 261;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.horasExtraTxt = new global::Gtk.Entry ();
			this.horasExtraTxt.WidthRequest = 110;
			this.horasExtraTxt.CanFocus = true;
			this.horasExtraTxt.Name = "horasExtraTxt";
			this.horasExtraTxt.IsEditable = true;
			this.horasExtraTxt.InvisibleChar = '●';
			this.fixed5.Add (this.horasExtraTxt);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.horasExtraTxt]));
			w28.X = 596;
			w28.Y = 256;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Comentario:");
			this.fixed5.Add (this.label13);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label13]));
			w29.X = 313;
			w29.Y = 291;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.comentario = new global::Gtk.TextView ();
			this.comentario.WidthRequest = 387;
			this.comentario.HeightRequest = 82;
			this.comentario.CanFocus = true;
			this.comentario.Name = "comentario";
			this.GtkScrolledWindow1.Add (this.comentario);
			this.fixed5.Add (this.GtkScrolledWindow1);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.GtkScrolledWindow1]));
			w31.X = 315;
			w31.Y = 321;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.cancelar = new global::Gtk.Button ();
			this.cancelar.CanFocus = true;
			this.cancelar.Name = "cancelar";
			this.cancelar.UseUnderline = true;
			this.cancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.fixed5.Add (this.cancelar);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.cancelar]));
			w32.X = 569;
			w32.Y = 426;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.pagar = new global::Gtk.Button ();
			this.pagar.CanFocus = true;
			this.pagar.Name = "pagar";
			this.pagar.UseUnderline = true;
			this.pagar.Label = global::Mono.Unix.Catalog.GetString ("Validar Pago");
			this.fixed5.Add (this.pagar);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.pagar]));
			w33.X = 638;
			w33.Y = 426;
			this.Add (this.fixed5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 934;
			this.DefaultHeight = 514;
			this.Show ();
			this.carger.Clicked += new global::System.EventHandler (this.OnCargerClicked);
			this.cancelar.Clicked += new global::System.EventHandler (this.OnCanselarClicked);
			this.pagar.Clicked += new global::System.EventHandler (this.OnPagarClicked);
		}
	}
}
