
// This file has been generated by the GUI designer. Do not modify.
namespace EscuelaPrimaria
{
	public partial class EditarAlumno
	{
		private global::Gtk.Fixed fixed5;
		private global::Gtk.Image image1;
		private global::Gtk.Image image2;
		private global::Gtk.Entry telEmTxt;
		private global::Gtk.Entry aviTxt;
		private global::Gtk.Entry telTxt;
		private global::Gtk.Entry colTxt;
		private global::Gtk.Entry ciudadText;
		private global::Gtk.Entry numIntTex;
		private global::Gtk.Label label20;
		private global::Gtk.Label label19;
		private global::Gtk.Label label18;
		private global::Gtk.Label label17;
		private global::Gtk.Label label16;
		private global::Gtk.Label label1;
		private global::Gtk.Label label15;
		private global::Gtk.Entry numExtTxt;
		private global::Gtk.Entry codTxt;
		private global::Gtk.Entry nomTxt;
		private global::Gtk.Entry paternoTxt;
		private global::Gtk.Entry maternoTxt;
		private global::Gtk.Entry calleTxt;
		private global::Gtk.Label label14;
		private global::Gtk.Label label13;
		private global::Gtk.Label label12;
		private global::Gtk.Label label11;
		private global::Gtk.Label label10;
		private global::Gtk.Label label9;
		private global::Gtk.Label label4;
		private global::Gtk.Entry passwordText;
		private global::Gtk.Label label3;
		private global::Gtk.Entry usuarioText;
		private global::Gtk.Label label2;
		private global::Gtk.Label label5;
		private global::Gtk.Button carger;
		private global::Gtk.Button guardar;
		private global::Gtk.Button eliminar;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView nodeview1;
		private global::Gtk.Label idLabel;
		private global::Gtk.Entry idTxt;
		private global::Gtk.Button canselar;
		private global::Gtk.Image image6;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EscuelaPrimaria.EditarAlumno
			this.Name = "EscuelaPrimaria.EditarAlumno";
			this.Title = global::Mono.Unix.Catalog.GetString ("Editar Alumno");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child EscuelaPrimaria.EditarAlumno.Gtk.Container+ContainerChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.ColorAzul.png");
			this.fixed5.Add (this.image1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.image1]));
			w1.X = 3;
			w1.Y = 3;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.editarAlumno.png");
			this.fixed5.Add (this.image2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.image2]));
			w2.X = 7;
			w2.Y = 4;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.telEmTxt = new global::Gtk.Entry ();
			this.telEmTxt.CanFocus = true;
			this.telEmTxt.Name = "telEmTxt";
			this.telEmTxt.IsEditable = true;
			this.telEmTxt.InvisibleChar = '●';
			this.fixed5.Add (this.telEmTxt);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.telEmTxt]));
			w3.X = 668;
			w3.Y = 416;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.aviTxt = new global::Gtk.Entry ();
			this.aviTxt.CanFocus = true;
			this.aviTxt.Name = "aviTxt";
			this.aviTxt.IsEditable = true;
			this.aviTxt.InvisibleChar = '●';
			this.fixed5.Add (this.aviTxt);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.aviTxt]));
			w4.X = 668;
			w4.Y = 381;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.telTxt = new global::Gtk.Entry ();
			this.telTxt.CanFocus = true;
			this.telTxt.Name = "telTxt";
			this.telTxt.IsEditable = true;
			this.telTxt.InvisibleChar = '●';
			this.fixed5.Add (this.telTxt);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.telTxt]));
			w5.X = 667;
			w5.Y = 346;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.colTxt = new global::Gtk.Entry ();
			this.colTxt.CanFocus = true;
			this.colTxt.Name = "colTxt";
			this.colTxt.IsEditable = true;
			this.colTxt.InvisibleChar = '●';
			this.fixed5.Add (this.colTxt);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.colTxt]));
			w6.X = 667;
			w6.Y = 311;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.ciudadText = new global::Gtk.Entry ();
			this.ciudadText.CanFocus = true;
			this.ciudadText.Name = "ciudadText";
			this.ciudadText.IsEditable = true;
			this.ciudadText.InvisibleChar = '●';
			this.fixed5.Add (this.ciudadText);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.ciudadText]));
			w7.X = 666;
			w7.Y = 275;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.numIntTex = new global::Gtk.Entry ();
			this.numIntTex.CanFocus = true;
			this.numIntTex.Name = "numIntTex";
			this.numIntTex.IsEditable = true;
			this.numIntTex.InvisibleChar = '●';
			this.fixed5.Add (this.numIntTex);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.numIntTex]));
			w8.X = 664;
			w8.Y = 240;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Emergencia:");
			this.fixed5.Add (this.label20);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label20]));
			w9.X = 591;
			w9.Y = 430;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Teléfono de");
			this.fixed5.Add (this.label19);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label19]));
			w10.X = 591;
			w10.Y = 414;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Avisar:");
			this.fixed5.Add (this.label18);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label18]));
			w11.X = 621;
			w11.Y = 386;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString (" Teléfono:");
			this.fixed5.Add (this.label17);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label17]));
			w12.X = 607;
			w12.Y = 351;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Colonia:");
			this.fixed5.Add (this.label16);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label16]));
			w13.X = 615;
			w13.Y = 319;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Ciudad:");
			this.fixed5.Add (this.label1);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label1]));
			w14.X = 619;
			w14.Y = 280;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString (" Numero Interior:");
			this.fixed5.Add (this.label15);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label15]));
			w15.X = 560;
			w15.Y = 245;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.numExtTxt = new global::Gtk.Entry ();
			this.numExtTxt.CanFocus = true;
			this.numExtTxt.Name = "numExtTxt";
			this.numExtTxt.IsEditable = true;
			this.numExtTxt.InvisibleChar = '●';
			this.fixed5.Add (this.numExtTxt);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.numExtTxt]));
			w16.X = 402;
			w16.Y = 420;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.codTxt = new global::Gtk.Entry ();
			this.codTxt.CanFocus = true;
			this.codTxt.Name = "codTxt";
			this.codTxt.IsEditable = true;
			this.codTxt.InvisibleChar = '●';
			this.fixed5.Add (this.codTxt);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.codTxt]));
			w17.X = 394;
			w17.Y = 239;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.nomTxt = new global::Gtk.Entry ();
			this.nomTxt.CanFocus = true;
			this.nomTxt.Name = "nomTxt";
			this.nomTxt.IsEditable = true;
			this.nomTxt.InvisibleChar = '●';
			this.fixed5.Add (this.nomTxt);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.nomTxt]));
			w18.X = 395;
			w18.Y = 273;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.paternoTxt = new global::Gtk.Entry ();
			this.paternoTxt.CanFocus = true;
			this.paternoTxt.Name = "paternoTxt";
			this.paternoTxt.IsEditable = true;
			this.paternoTxt.InvisibleChar = '●';
			this.fixed5.Add (this.paternoTxt);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.paternoTxt]));
			w19.X = 396;
			w19.Y = 308;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.maternoTxt = new global::Gtk.Entry ();
			this.maternoTxt.CanFocus = true;
			this.maternoTxt.Name = "maternoTxt";
			this.maternoTxt.IsEditable = true;
			this.maternoTxt.InvisibleChar = '●';
			this.fixed5.Add (this.maternoTxt);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.maternoTxt]));
			w20.X = 397;
			w20.Y = 348;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.calleTxt = new global::Gtk.Entry ();
			this.calleTxt.CanFocus = true;
			this.calleTxt.Name = "calleTxt";
			this.calleTxt.IsEditable = true;
			this.calleTxt.InvisibleChar = '●';
			this.fixed5.Add (this.calleTxt);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.calleTxt]));
			w21.X = 399;
			w21.Y = 383;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero:");
			this.fixed5.Add (this.label14);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label14]));
			w22.X = 345;
			w22.Y = 422;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Calle:");
			this.fixed5.Add (this.label13);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label13]));
			w23.X = 361;
			w23.Y = 385;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido Materno:");
			this.fixed5.Add (this.label12);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label12]));
			w24.X = 294;
			w24.Y = 353;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido Paterno:");
			this.fixed5.Add (this.label11);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label11]));
			w25.X = 294;
			w25.Y = 309;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.fixed5.Add (this.label10);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label10]));
			w26.X = 340;
			w26.Y = 278;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Código:");
			this.fixed5.Add (this.label9);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label9]));
			w27.X = 345;
			w27.Y = 241;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Datos Personales");
			this.fixed5.Add (this.label4);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label4]));
			w28.X = 533;
			w28.Y = 207;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.passwordText = new global::Gtk.Entry ();
			this.passwordText.CanFocus = true;
			this.passwordText.Name = "passwordText";
			this.passwordText.IsEditable = true;
			this.passwordText.InvisibleChar = '●';
			this.fixed5.Add (this.passwordText);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.passwordText]));
			w29.X = 662;
			w29.Y = 173;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
			this.fixed5.Add (this.label3);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label3]));
			w30.X = 599;
			w30.Y = 177;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.usuarioText = new global::Gtk.Entry ();
			this.usuarioText.CanFocus = true;
			this.usuarioText.Name = "usuarioText";
			this.usuarioText.IsEditable = true;
			this.usuarioText.InvisibleChar = '●';
			this.fixed5.Add (this.usuarioText);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.usuarioText]));
			w31.X = 391;
			w31.Y = 177;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Usuario:");
			this.fixed5.Add (this.label2);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label2]));
			w32.X = 340;
			w32.Y = 178;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Nuevo Usuario");
			this.fixed5.Add (this.label5);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label5]));
			w33.X = 535;
			w33.Y = 141;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.carger = new global::Gtk.Button ();
			this.carger.CanFocus = true;
			this.carger.Name = "carger";
			this.carger.UseUnderline = true;
			this.carger.Label = global::Mono.Unix.Catalog.GetString ("Cargar");
			this.fixed5.Add (this.carger);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.carger]));
			w34.X = 23;
			w34.Y = 459;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.guardar = new global::Gtk.Button ();
			this.guardar.CanFocus = true;
			this.guardar.Name = "guardar";
			this.guardar.UseUnderline = true;
			this.guardar.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
			this.fixed5.Add (this.guardar);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.guardar]));
			w35.X = 82;
			w35.Y = 460;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.eliminar = new global::Gtk.Button ();
			this.eliminar.CanFocus = true;
			this.eliminar.Name = "eliminar";
			this.eliminar.UseUnderline = true;
			this.eliminar.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
			this.fixed5.Add (this.eliminar);
			global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.eliminar]));
			w36.X = 149;
			w36.Y = 460;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.TreeView ();
			this.nodeview1.WidthRequest = 251;
			this.nodeview1.HeightRequest = 330;
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.GtkScrolledWindow.Add (this.nodeview1);
			this.fixed5.Add (this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.GtkScrolledWindow]));
			w38.X = 13;
			w38.Y = 101;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.idLabel = new global::Gtk.Label ();
			this.idLabel.Name = "idLabel";
			this.idLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("ID:");
			this.fixed5.Add (this.idLabel);
			global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.idLabel]));
			w39.X = 338;
			w39.Y = 99;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.idTxt = new global::Gtk.Entry ();
			this.idTxt.WidthRequest = 35;
			this.idTxt.CanFocus = true;
			this.idTxt.Name = "idTxt";
			this.idTxt.IsEditable = false;
			this.idTxt.InvisibleChar = '●';
			this.fixed5.Add (this.idTxt);
			global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.idTxt]));
			w40.X = 357;
			w40.Y = 94;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.canselar = new global::Gtk.Button ();
			this.canselar.CanFocus = true;
			this.canselar.Name = "canselar";
			this.canselar.UseUnderline = true;
			this.canselar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.fixed5.Add (this.canselar);
			global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.canselar]));
			w41.X = 216;
			w41.Y = 460;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.EscuelaPrimaria3.png");
			this.fixed5.Add (this.image6);
			global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.image6]));
			w42.X = 554;
			w42.Y = 4;
			this.Add (this.fixed5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 866;
			this.DefaultHeight = 547;
			this.Show ();
			this.carger.Clicked += new global::System.EventHandler (this.OnCargerClicked);
			this.guardar.Clicked += new global::System.EventHandler (this.OnGuardarClicked);
			this.eliminar.Clicked += new global::System.EventHandler (this.OnEliminarClicked);
			this.canselar.Clicked += new global::System.EventHandler (this.OnCanselarClicked);
		}
	}
}
