
// This file has been generated by the GUI designer. Do not modify.
namespace EscuelaPrimaria
{
	public partial class Cordinacion
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Image image2;
		private global::Gtk.Label labelNombre;
		private global::Gtk.Label cargoText;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Image image1;
		private global::Gtk.Button buttonNuevo;
		private global::Gtk.Button nuevoProfe;
		private global::Gtk.Button editarAlumno;
		private global::Gtk.Button pagosAlumno;
		private global::Gtk.Button matAlumno;
		private global::Gtk.Button editarProfe;
		private global::Gtk.Button nomina;
		private global::Gtk.Button nuevoCoord;
		private global::Gtk.Button editarCoord;
		private global::Gtk.Label idTexto;
		private global::Gtk.Button CursosAlumno;
		private global::Gtk.Button gradoAlumno;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EscuelaPrimaria.Cordinacion
			this.Name = "EscuelaPrimaria.Cordinacion";
			this.Title = global::Mono.Unix.Catalog.GetString ("Cordimacion");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child EscuelaPrimaria.Cordinacion.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 66;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.EscuelaPrimaria3.png");
			this.fixed1.Add (this.image2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.image2]));
			w1.X = 337;
			w1.Y = 4;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelNombre = new global::Gtk.Label ();
			this.labelNombre.Name = "labelNombre";
			this.fixed1.Add (this.labelNombre);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.labelNombre]));
			w2.X = 16;
			w2.Y = 21;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cargoText = new global::Gtk.Label ();
			this.cargoText.Name = "cargoText";
			this.cargoText.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.fixed1.Add (this.cargoText);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.cargoText]));
			w3.X = 15;
			w3.Y = 39;
			this.vbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.Coordi.png");
			this.fixed2.Add (this.image1);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image1]));
			w5.X = 3;
			w5.Y = 3;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.buttonNuevo = new global::Gtk.Button ();
			this.buttonNuevo.CanFocus = true;
			this.buttonNuevo.Name = "buttonNuevo";
			this.buttonNuevo.UseUnderline = true;
			this.buttonNuevo.Label = global::Mono.Unix.Catalog.GetString ("Nuevo");
			this.fixed2.Add (this.buttonNuevo);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.buttonNuevo]));
			w6.X = 46;
			w6.Y = 102;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.nuevoProfe = new global::Gtk.Button ();
			this.nuevoProfe.CanFocus = true;
			this.nuevoProfe.Name = "nuevoProfe";
			this.nuevoProfe.UseUnderline = true;
			this.nuevoProfe.Label = global::Mono.Unix.Catalog.GetString ("Nuevo");
			this.fixed2.Add (this.nuevoProfe);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.nuevoProfe]));
			w7.X = 48;
			w7.Y = 208;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.editarAlumno = new global::Gtk.Button ();
			this.editarAlumno.CanFocus = true;
			this.editarAlumno.Name = "editarAlumno";
			this.editarAlumno.UseUnderline = true;
			this.editarAlumno.Label = global::Mono.Unix.Catalog.GetString ("Editar");
			this.fixed2.Add (this.editarAlumno);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.editarAlumno]));
			w8.X = 101;
			w8.Y = 102;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.pagosAlumno = new global::Gtk.Button ();
			this.pagosAlumno.CanFocus = true;
			this.pagosAlumno.Name = "pagosAlumno";
			this.pagosAlumno.UseUnderline = true;
			this.pagosAlumno.Label = global::Mono.Unix.Catalog.GetString ("Pagos");
			this.fixed2.Add (this.pagosAlumno);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.pagosAlumno]));
			w9.X = 155;
			w9.Y = 103;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.matAlumno = new global::Gtk.Button ();
			this.matAlumno.CanFocus = true;
			this.matAlumno.Name = "matAlumno";
			this.matAlumno.UseUnderline = true;
			this.matAlumno.Label = global::Mono.Unix.Catalog.GetString ("Materias");
			this.fixed2.Add (this.matAlumno);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.matAlumno]));
			w10.X = 207;
			w10.Y = 103;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.editarProfe = new global::Gtk.Button ();
			this.editarProfe.CanFocus = true;
			this.editarProfe.Name = "editarProfe";
			this.editarProfe.UseUnderline = true;
			this.editarProfe.Label = global::Mono.Unix.Catalog.GetString ("Editar");
			this.fixed2.Add (this.editarProfe);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.editarProfe]));
			w11.X = 99;
			w11.Y = 209;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.nomina = new global::Gtk.Button ();
			this.nomina.CanFocus = true;
			this.nomina.Name = "nomina";
			this.nomina.UseUnderline = true;
			this.nomina.Label = global::Mono.Unix.Catalog.GetString ("Nomina");
			this.fixed2.Add (this.nomina);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.nomina]));
			w12.X = 150;
			w12.Y = 209;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.nuevoCoord = new global::Gtk.Button ();
			this.nuevoCoord.CanFocus = true;
			this.nuevoCoord.Name = "nuevoCoord";
			this.nuevoCoord.UseUnderline = true;
			this.nuevoCoord.Label = global::Mono.Unix.Catalog.GetString ("Nuevo");
			this.fixed2.Add (this.nuevoCoord);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.nuevoCoord]));
			w13.X = 49;
			w13.Y = 315;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.editarCoord = new global::Gtk.Button ();
			this.editarCoord.CanFocus = true;
			this.editarCoord.Name = "editarCoord";
			this.editarCoord.UseUnderline = true;
			this.editarCoord.Label = global::Mono.Unix.Catalog.GetString ("Editar");
			this.fixed2.Add (this.editarCoord);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.editarCoord]));
			w14.X = 101;
			w14.Y = 315;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.idTexto = new global::Gtk.Label ();
			this.idTexto.Name = "idTexto";
			this.idTexto.LabelProp = global::Mono.Unix.Catalog.GetString ("id");
			this.fixed2.Add (this.idTexto);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.idTexto]));
			w15.X = 591;
			w15.Y = 367;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.CursosAlumno = new global::Gtk.Button ();
			this.CursosAlumno.CanFocus = true;
			this.CursosAlumno.Name = "CursosAlumno";
			this.CursosAlumno.UseUnderline = true;
			this.CursosAlumno.Label = global::Mono.Unix.Catalog.GetString ("Cursos");
			this.fixed2.Add (this.CursosAlumno);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.CursosAlumno]));
			w16.X = 274;
			w16.Y = 103;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.gradoAlumno = new global::Gtk.Button ();
			this.gradoAlumno.CanFocus = true;
			this.gradoAlumno.Name = "gradoAlumno";
			this.gradoAlumno.UseUnderline = true;
			this.gradoAlumno.Label = global::Mono.Unix.Catalog.GetString ("Grado");
			this.fixed2.Add (this.gradoAlumno);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.gradoAlumno]));
			w17.X = 331;
			w17.Y = 104;
			this.vbox1.Add (this.fixed2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed2]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 665;
			this.DefaultHeight = 510;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.buttonNuevo.Clicked += new global::System.EventHandler (this.OnButtonNuevoClicked);
			this.nuevoProfe.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
			this.editarAlumno.Clicked += new global::System.EventHandler (this.OnEditarAlumnoClicked);
			this.pagosAlumno.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
			this.matAlumno.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
			this.editarProfe.Clicked += new global::System.EventHandler (this.OnButton6Clicked);
			this.nomina.Clicked += new global::System.EventHandler (this.OnButton7Clicked);
			this.nuevoCoord.Clicked += new global::System.EventHandler (this.OnButton9Clicked);
			this.editarCoord.Clicked += new global::System.EventHandler (this.OnButton10Clicked);
			this.CursosAlumno.Clicked += new global::System.EventHandler (this.OnButton8Clicked);
			this.gradoAlumno.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		}
	}
}
