
// This file has been generated by the GUI designer. Do not modify.
namespace EscuelaPrimaria
{
	public partial class Alumnos
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Image image9;
		private global::Gtk.Label gradoText;
		private global::Gtk.Label labelNombre;
		private global::Gtk.Notebook notebook2;
		private global::Gtk.Fixed fixed5;
		private global::Gtk.Image image1;
		private global::Gtk.Image image2;
		private global::Gtk.Entry telEmTxt;
		private global::Gtk.Entry aviTxt;
		private global::Gtk.Entry telTxt;
		private global::Gtk.Entry colTxt;
		private global::Gtk.Entry ciudadText;
		private global::Gtk.Entry numIntTex;
		private global::Gtk.Label label19;
		private global::Gtk.Label label20;
		private global::Gtk.Label label18;
		private global::Gtk.Label label17;
		private global::Gtk.Label label16;
		private global::Gtk.Label label15;
		private global::Gtk.Label label1;
		private global::Gtk.Entry codTxt;
		private global::Gtk.Entry nomTxt;
		private global::Gtk.Entry paternoTxt;
		private global::Gtk.Entry maternoTxt;
		private global::Gtk.Entry calleTxt;
		private global::Gtk.Entry numExtTxt;
		private global::Gtk.Label label14;
		private global::Gtk.Label label13;
		private global::Gtk.Label label12;
		private global::Gtk.Label label11;
		private global::Gtk.Label label9;
		private global::Gtk.Label label10;
		private global::Gtk.Label label4;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Image image3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView nodeMateria;
		private global::Gtk.Image image4;
		private global::Gtk.Label label5;
		private global::Gtk.Fixed fixed3;
		private global::Gtk.Image image5;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView nodeCursos;
		private global::Gtk.Image image7;
		private global::Gtk.Label label6;
		private global::Gtk.Fixed fixed4;
		private global::Gtk.Image image6;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TreeView nodePagos;
		private global::Gtk.Image image8;
		private global::Gtk.Label label7;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EscuelaPrimaria.Alumnos
			this.Name = "EscuelaPrimaria.Alumnos";
			this.Title = global::Mono.Unix.Catalog.GetString ("Alumnos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child EscuelaPrimaria.Alumnos.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 66;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image9 = new global::Gtk.Image ();
			this.image9.Name = "image9";
			this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.EscuelaPrimaria3.png");
			this.fixed1.Add (this.image9);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.image9]));
			w1.X = 340;
			w1.Y = 3;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.gradoText = new global::Gtk.Label ();
			this.gradoText.Name = "gradoText";
			this.gradoText.LabelProp = global::Mono.Unix.Catalog.GetString ("Grado:");
			this.fixed1.Add (this.gradoText);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.gradoText]));
			w2.X = 17;
			w2.Y = 37;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelNombre = new global::Gtk.Label ();
			this.labelNombre.Name = "labelNombre";
			this.labelNombre.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
			this.fixed1.Add (this.labelNombre);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.labelNombre]));
			w3.X = 16;
			w3.Y = 10;
			this.vbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 1;
			this.notebook2.Scrollable = true;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.ColorAzul6.png");
			this.fixed5.Add (this.image1);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.image1]));
			w5.X = 3;
			w5.Y = 3;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.DatPer.png");
			this.fixed5.Add (this.image2);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.image2]));
			w6.X = 7;
			w6.Y = 4;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.telEmTxt = new global::Gtk.Entry ();
			this.telEmTxt.CanFocus = true;
			this.telEmTxt.Name = "telEmTxt";
			this.telEmTxt.IsEditable = true;
			this.telEmTxt.InvisibleChar = '●';
			this.fixed5.Add (this.telEmTxt);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.telEmTxt]));
			w7.X = 429;
			w7.Y = 325;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.aviTxt = new global::Gtk.Entry ();
			this.aviTxt.CanFocus = true;
			this.aviTxt.Name = "aviTxt";
			this.aviTxt.IsEditable = true;
			this.aviTxt.InvisibleChar = '●';
			this.fixed5.Add (this.aviTxt);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.aviTxt]));
			w8.X = 428;
			w8.Y = 290;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.telTxt = new global::Gtk.Entry ();
			this.telTxt.CanFocus = true;
			this.telTxt.Name = "telTxt";
			this.telTxt.IsEditable = true;
			this.telTxt.InvisibleChar = '●';
			this.fixed5.Add (this.telTxt);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.telTxt]));
			w9.X = 428;
			w9.Y = 250;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.colTxt = new global::Gtk.Entry ();
			this.colTxt.CanFocus = true;
			this.colTxt.Name = "colTxt";
			this.colTxt.IsEditable = true;
			this.colTxt.InvisibleChar = '●';
			this.fixed5.Add (this.colTxt);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.colTxt]));
			w10.X = 427;
			w10.Y = 211;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.ciudadText = new global::Gtk.Entry ();
			this.ciudadText.CanFocus = true;
			this.ciudadText.Name = "ciudadText";
			this.ciudadText.IsEditable = true;
			this.ciudadText.InvisibleChar = '●';
			this.fixed5.Add (this.ciudadText);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.ciudadText]));
			w11.X = 425;
			w11.Y = 173;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.numIntTex = new global::Gtk.Entry ();
			this.numIntTex.CanFocus = true;
			this.numIntTex.Name = "numIntTex";
			this.numIntTex.IsEditable = true;
			this.numIntTex.InvisibleChar = '●';
			this.fixed5.Add (this.numIntTex);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.numIntTex]));
			w12.X = 423;
			w12.Y = 137;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Teléfono de");
			this.fixed5.Add (this.label19);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label19]));
			w13.X = 354;
			w13.Y = 322;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Emergencia:");
			this.fixed5.Add (this.label20);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label20]));
			w14.X = 354;
			w14.Y = 338;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Avisar:");
			this.fixed5.Add (this.label18);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label18]));
			w15.X = 384;
			w15.Y = 295;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString (" Teléfono:");
			this.fixed5.Add (this.label17);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label17]));
			w16.X = 364;
			w16.Y = 256;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Colonia:");
			this.fixed5.Add (this.label16);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label16]));
			w17.X = 376;
			w17.Y = 217;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString (" Numero Interior:");
			this.fixed5.Add (this.label15);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label15]));
			w18.X = 319;
			w18.Y = 142;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Ciudad:");
			this.fixed5.Add (this.label1);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label1]));
			w19.X = 376;
			w19.Y = 179;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.codTxt = new global::Gtk.Entry ();
			this.codTxt.CanFocus = true;
			this.codTxt.Name = "codTxt";
			this.codTxt.IsEditable = true;
			this.codTxt.InvisibleChar = '●';
			this.fixed5.Add (this.codTxt);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.codTxt]));
			w20.X = 146;
			w20.Y = 140;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.nomTxt = new global::Gtk.Entry ();
			this.nomTxt.CanFocus = true;
			this.nomTxt.Name = "nomTxt";
			this.nomTxt.IsEditable = true;
			this.nomTxt.InvisibleChar = '●';
			this.fixed5.Add (this.nomTxt);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.nomTxt]));
			w21.X = 148;
			w21.Y = 176;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.paternoTxt = new global::Gtk.Entry ();
			this.paternoTxt.CanFocus = true;
			this.paternoTxt.Name = "paternoTxt";
			this.paternoTxt.IsEditable = true;
			this.paternoTxt.InvisibleChar = '●';
			this.fixed5.Add (this.paternoTxt);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.paternoTxt]));
			w22.X = 149;
			w22.Y = 211;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.maternoTxt = new global::Gtk.Entry ();
			this.maternoTxt.CanFocus = true;
			this.maternoTxt.Name = "maternoTxt";
			this.maternoTxt.IsEditable = true;
			this.maternoTxt.InvisibleChar = '●';
			this.fixed5.Add (this.maternoTxt);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.maternoTxt]));
			w23.X = 151;
			w23.Y = 248;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.calleTxt = new global::Gtk.Entry ();
			this.calleTxt.CanFocus = true;
			this.calleTxt.Name = "calleTxt";
			this.calleTxt.IsEditable = true;
			this.calleTxt.InvisibleChar = '●';
			this.fixed5.Add (this.calleTxt);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.calleTxt]));
			w24.X = 150;
			w24.Y = 288;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.numExtTxt = new global::Gtk.Entry ();
			this.numExtTxt.CanFocus = true;
			this.numExtTxt.Name = "numExtTxt";
			this.numExtTxt.IsEditable = true;
			this.numExtTxt.InvisibleChar = '●';
			this.fixed5.Add (this.numExtTxt);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.numExtTxt]));
			w25.X = 150;
			w25.Y = 323;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero:");
			this.fixed5.Add (this.label14);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label14]));
			w26.X = 95;
			w26.Y = 330;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Calle:");
			this.fixed5.Add (this.label13);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label13]));
			w27.X = 113;
			w27.Y = 295;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido Materno:");
			this.fixed5.Add (this.label12);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label12]));
			w28.X = 46;
			w28.Y = 253;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido Paterno:");
			this.fixed5.Add (this.label11);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label11]));
			w29.X = 47;
			w29.Y = 213;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Código:");
			this.fixed5.Add (this.label9);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label9]));
			w30.X = 98;
			w30.Y = 143;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.fixed5.Add (this.label10);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label10]));
			w31.X = 93;
			w31.Y = 180;
			this.notebook2.Add (this.fixed5);
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Datos Personales");
			this.notebook2.SetTabLabel (this.fixed5, this.label4);
			this.label4.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image3 = new global::Gtk.Image ();
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.RedBajito.png");
			this.fixed2.Add (this.image3);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image3]));
			w33.X = 5;
			w33.Y = 3;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeMateria = new global::Gtk.TreeView ();
			this.nodeMateria.WidthRequest = 553;
			this.nodeMateria.HeightRequest = 248;
			this.nodeMateria.CanFocus = true;
			this.nodeMateria.Name = "nodeMateria";
			this.GtkScrolledWindow.Add (this.nodeMateria);
			this.fixed2.Add (this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.GtkScrolledWindow]));
			w35.X = 31;
			w35.Y = 107;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image4 = new global::Gtk.Image ();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.materias.png");
			this.fixed2.Add (this.image4);
			global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image4]));
			w36.X = 7;
			w36.Y = 5;
			this.notebook2.Add (this.fixed2);
			global::Gtk.Notebook.NotebookChild w37 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.fixed2]));
			w37.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Materias");
			this.notebook2.SetTabLabel (this.fixed2, this.label5);
			this.label5.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.ColorAzul6.png");
			this.fixed3.Add (this.image5);
			global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.image5]));
			w38.X = 3;
			w38.Y = 3;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.nodeCursos = new global::Gtk.TreeView ();
			this.nodeCursos.WidthRequest = 553;
			this.nodeCursos.HeightRequest = 248;
			this.nodeCursos.CanFocus = true;
			this.nodeCursos.Name = "nodeCursos";
			this.GtkScrolledWindow1.Add (this.nodeCursos);
			this.fixed3.Add (this.GtkScrolledWindow1);
			global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.GtkScrolledWindow1]));
			w40.X = 31;
			w40.Y = 105;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.image7 = new global::Gtk.Image ();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.Cursos.png");
			this.fixed3.Add (this.image7);
			global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.image7]));
			w41.X = 4;
			w41.Y = 4;
			this.notebook2.Add (this.fixed3);
			global::Gtk.Notebook.NotebookChild w42 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.fixed3]));
			w42.Position = 2;
			// Notebook tab
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Cursos");
			this.notebook2.SetTabLabel (this.fixed3, this.label6);
			this.label6.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.RedBajito.png");
			this.fixed4.Add (this.image6);
			global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.image6]));
			w43.X = 2;
			w43.Y = 3;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.nodePagos = new global::Gtk.TreeView ();
			this.nodePagos.WidthRequest = 553;
			this.nodePagos.HeightRequest = 248;
			this.nodePagos.CanFocus = true;
			this.nodePagos.Name = "nodePagos";
			this.GtkScrolledWindow2.Add (this.nodePagos);
			this.fixed4.Add (this.GtkScrolledWindow2);
			global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.GtkScrolledWindow2]));
			w45.X = 24;
			w45.Y = 100;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.image8 = new global::Gtk.Image ();
			this.image8.Name = "image8";
			this.image8.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.Pagos.png");
			this.fixed4.Add (this.image8);
			global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.image8]));
			w46.X = 3;
			w46.Y = 3;
			this.notebook2.Add (this.fixed4);
			global::Gtk.Notebook.NotebookChild w47 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.fixed4]));
			w47.Position = 3;
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Pagos");
			this.notebook2.SetTabLabel (this.fixed4, this.label7);
			this.label7.ShowAll ();
			this.vbox1.Add (this.notebook2);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook2]));
			w48.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 657;
			this.DefaultHeight = 539;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
