
// This file has been generated by the GUI designer. Do not modify.
namespace EscuelaPrimaria
{
	public partial class NuevoCordinacion
	{
		private global::Gtk.Fixed fixed5;
		private global::Gtk.Image image1;
		private global::Gtk.Image image2;
		private global::Gtk.Image image3;
		private global::Gtk.Button canselar;
		private global::Gtk.Button guardar;
		private global::Gtk.Entry telEmTxtEst;
		private global::Gtk.Entry aviTxtEst;
		private global::Gtk.Entry telTxtEst;
		private global::Gtk.Entry colTxtEst;
		private global::Gtk.Entry ciudadTextEst;
		private global::Gtk.Entry numIntTexEst;
		private global::Gtk.Entry numExtTxtEst;
		private global::Gtk.Entry calleTxtEst;
		private global::Gtk.Entry maternoTxtEst;
		private global::Gtk.Entry paternoTxtEst;
		private global::Gtk.Entry nomTxtEst;
		private global::Gtk.Entry codTxtEst;
		private global::Gtk.Label label20;
		private global::Gtk.Label label19;
		private global::Gtk.Label label18;
		private global::Gtk.Label label17;
		private global::Gtk.Label label16;
		private global::Gtk.Label label1;
		private global::Gtk.Label label15;
		private global::Gtk.Label label14;
		private global::Gtk.Label label13;
		private global::Gtk.Label label12;
		private global::Gtk.Label label11;
		private global::Gtk.Label label10;
		private global::Gtk.Label label9;
		private global::Gtk.Entry passwordTextEst;
		private global::Gtk.Label label3;
		private global::Gtk.Entry usuarioTextEst;
		private global::Gtk.Label label2;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Entry cargoText;
		private global::Gtk.Label label6;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EscuelaPrimaria.NuevoCordinacion
			this.Name = "EscuelaPrimaria.NuevoCordinacion";
			this.Title = global::Mono.Unix.Catalog.GetString ("NuevoCordinacion");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child EscuelaPrimaria.NuevoCordinacion.Gtk.Container+ContainerChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.ColorAzul6.png");
			this.fixed5.Add (this.image1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.image1]));
			w1.X = 3;
			w1.Y = 3;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.nuevoPuesto.png");
			this.fixed5.Add (this.image2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.image2]));
			w2.X = 7;
			w2.Y = 4;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image3 = new global::Gtk.Image ();
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.Imagen1.png");
			this.fixed5.Add (this.image3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.image3]));
			w3.X = 3;
			w3.Y = 389;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.canselar = new global::Gtk.Button ();
			this.canselar.CanFocus = true;
			this.canselar.Name = "canselar";
			this.canselar.UseUnderline = true;
			this.canselar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.fixed5.Add (this.canselar);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.canselar]));
			w4.X = 477;
			w4.Y = 408;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.guardar = new global::Gtk.Button ();
			this.guardar.CanFocus = true;
			this.guardar.Name = "guardar";
			this.guardar.UseUnderline = true;
			this.guardar.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
			this.fixed5.Add (this.guardar);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.guardar]));
			w5.X = 548;
			w5.Y = 408;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.telEmTxtEst = new global::Gtk.Entry ();
			this.telEmTxtEst.CanFocus = true;
			this.telEmTxtEst.Name = "telEmTxtEst";
			this.telEmTxtEst.IsEditable = true;
			this.telEmTxtEst.InvisibleChar = '●';
			this.fixed5.Add (this.telEmTxtEst);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.telEmTxtEst]));
			w6.X = 445;
			w6.Y = 357;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.aviTxtEst = new global::Gtk.Entry ();
			this.aviTxtEst.CanFocus = true;
			this.aviTxtEst.Name = "aviTxtEst";
			this.aviTxtEst.IsEditable = true;
			this.aviTxtEst.InvisibleChar = '●';
			this.fixed5.Add (this.aviTxtEst);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.aviTxtEst]));
			w7.X = 444;
			w7.Y = 324;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.telTxtEst = new global::Gtk.Entry ();
			this.telTxtEst.CanFocus = true;
			this.telTxtEst.Name = "telTxtEst";
			this.telTxtEst.IsEditable = true;
			this.telTxtEst.InvisibleChar = '●';
			this.fixed5.Add (this.telTxtEst);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.telTxtEst]));
			w8.X = 445;
			w8.Y = 291;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.colTxtEst = new global::Gtk.Entry ();
			this.colTxtEst.CanFocus = true;
			this.colTxtEst.Name = "colTxtEst";
			this.colTxtEst.IsEditable = true;
			this.colTxtEst.InvisibleChar = '●';
			this.fixed5.Add (this.colTxtEst);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.colTxtEst]));
			w9.X = 445;
			w9.Y = 258;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.ciudadTextEst = new global::Gtk.Entry ();
			this.ciudadTextEst.CanFocus = true;
			this.ciudadTextEst.Name = "ciudadTextEst";
			this.ciudadTextEst.IsEditable = true;
			this.ciudadTextEst.InvisibleChar = '●';
			this.fixed5.Add (this.ciudadTextEst);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.ciudadTextEst]));
			w10.X = 445;
			w10.Y = 225;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.numIntTexEst = new global::Gtk.Entry ();
			this.numIntTexEst.CanFocus = true;
			this.numIntTexEst.Name = "numIntTexEst";
			this.numIntTexEst.IsEditable = true;
			this.numIntTexEst.InvisibleChar = '●';
			this.fixed5.Add (this.numIntTexEst);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.numIntTexEst]));
			w11.X = 445;
			w11.Y = 190;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.numExtTxtEst = new global::Gtk.Entry ();
			this.numExtTxtEst.CanFocus = true;
			this.numExtTxtEst.Name = "numExtTxtEst";
			this.numExtTxtEst.IsEditable = true;
			this.numExtTxtEst.InvisibleChar = '●';
			this.fixed5.Add (this.numExtTxtEst);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.numExtTxtEst]));
			w12.X = 179;
			w12.Y = 358;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.calleTxtEst = new global::Gtk.Entry ();
			this.calleTxtEst.CanFocus = true;
			this.calleTxtEst.Name = "calleTxtEst";
			this.calleTxtEst.IsEditable = true;
			this.calleTxtEst.InvisibleChar = '●';
			this.fixed5.Add (this.calleTxtEst);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.calleTxtEst]));
			w13.X = 179;
			w13.Y = 326;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.maternoTxtEst = new global::Gtk.Entry ();
			this.maternoTxtEst.CanFocus = true;
			this.maternoTxtEst.Name = "maternoTxtEst";
			this.maternoTxtEst.IsEditable = true;
			this.maternoTxtEst.InvisibleChar = '●';
			this.fixed5.Add (this.maternoTxtEst);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.maternoTxtEst]));
			w14.X = 180;
			w14.Y = 292;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.paternoTxtEst = new global::Gtk.Entry ();
			this.paternoTxtEst.CanFocus = true;
			this.paternoTxtEst.Name = "paternoTxtEst";
			this.paternoTxtEst.IsEditable = true;
			this.paternoTxtEst.InvisibleChar = '●';
			this.fixed5.Add (this.paternoTxtEst);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.paternoTxtEst]));
			w15.X = 180;
			w15.Y = 260;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.nomTxtEst = new global::Gtk.Entry ();
			this.nomTxtEst.CanFocus = true;
			this.nomTxtEst.Name = "nomTxtEst";
			this.nomTxtEst.IsEditable = true;
			this.nomTxtEst.InvisibleChar = '●';
			this.fixed5.Add (this.nomTxtEst);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.nomTxtEst]));
			w16.X = 180;
			w16.Y = 227;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.codTxtEst = new global::Gtk.Entry ();
			this.codTxtEst.CanFocus = true;
			this.codTxtEst.Name = "codTxtEst";
			this.codTxtEst.IsEditable = true;
			this.codTxtEst.InvisibleChar = '●';
			this.fixed5.Add (this.codTxtEst);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.codTxtEst]));
			w17.X = 179;
			w17.Y = 194;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Emergencia:");
			this.fixed5.Add (this.label20);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label20]));
			w18.X = 369;
			w18.Y = 368;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Teléfono de");
			this.fixed5.Add (this.label19);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label19]));
			w19.X = 370;
			w19.Y = 352;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Avisar:");
			this.fixed5.Add (this.label18);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label18]));
			w20.X = 399;
			w20.Y = 328;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString (" Teléfono:");
			this.fixed5.Add (this.label17);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label17]));
			w21.X = 380;
			w21.Y = 294;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Colonia:");
			this.fixed5.Add (this.label16);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label16]));
			w22.X = 392;
			w22.Y = 262;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Ciudad:");
			this.fixed5.Add (this.label1);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label1]));
			w23.X = 396;
			w23.Y = 229;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString (" Numero Interior:");
			this.fixed5.Add (this.label15);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label15]));
			w24.X = 344;
			w24.Y = 192;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero:");
			this.fixed5.Add (this.label14);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label14]));
			w25.X = 126;
			w25.Y = 360;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Calle:");
			this.fixed5.Add (this.label13);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label13]));
			w26.X = 139;
			w26.Y = 329;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido Materno:");
			this.fixed5.Add (this.label12);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label12]));
			w27.X = 77;
			w27.Y = 295;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido Paterno:");
			this.fixed5.Add (this.label11);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label11]));
			w28.X = 78;
			w28.Y = 261;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.fixed5.Add (this.label10);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label10]));
			w29.X = 126;
			w29.Y = 229;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Código:");
			this.fixed5.Add (this.label9);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label9]));
			w30.X = 133;
			w30.Y = 197;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.passwordTextEst = new global::Gtk.Entry ();
			this.passwordTextEst.CanFocus = true;
			this.passwordTextEst.Name = "passwordTextEst";
			this.passwordTextEst.IsEditable = true;
			this.passwordTextEst.InvisibleChar = '●';
			this.fixed5.Add (this.passwordTextEst);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.passwordTextEst]));
			w31.X = 446;
			w31.Y = 109;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
			this.fixed5.Add (this.label3);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label3]));
			w32.X = 381;
			w32.Y = 113;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.usuarioTextEst = new global::Gtk.Entry ();
			this.usuarioTextEst.CanFocus = true;
			this.usuarioTextEst.Name = "usuarioTextEst";
			this.usuarioTextEst.IsEditable = true;
			this.usuarioTextEst.InvisibleChar = '●';
			this.fixed5.Add (this.usuarioTextEst);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.usuarioTextEst]));
			w33.X = 176;
			w33.Y = 106;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Usuario:");
			this.fixed5.Add (this.label2);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label2]));
			w34.X = 124;
			w34.Y = 107;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Datos Personales");
			this.fixed5.Add (this.label4);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label4]));
			w35.X = 311;
			w35.Y = 154;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Nuevo Usuario");
			this.fixed5.Add (this.label5);
			global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label5]));
			w36.X = 314;
			w36.Y = 75;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.cargoText = new global::Gtk.Entry ();
			this.cargoText.CanFocus = true;
			this.cargoText.Name = "cargoText";
			this.cargoText.IsEditable = true;
			this.cargoText.InvisibleChar = '●';
			this.fixed5.Add (this.cargoText);
			global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.cargoText]));
			w37.X = 221;
			w37.Y = 406;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Puesto:");
			this.fixed5.Add (this.label6);
			global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label6]));
			w38.X = 173;
			w38.Y = 411;
			this.Add (this.fixed5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 644;
			this.DefaultHeight = 491;
			this.Show ();
			this.canselar.Clicked += new global::System.EventHandler (this.OnCanselarClicked);
			this.guardar.Clicked += new global::System.EventHandler (this.OnGuardarClicked);
		}
	}
}
