
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label1;
	private global::Gtk.Image image2;
	private global::Gtk.Button entrar;
	private global::Gtk.Entry nombreTxt;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.ComboBox selecTxt;
	private global::Gtk.Entry contraTxt;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
		this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre de Usuario:");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w1.X = 49;
		w1.Y = 127;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.image2 = new global::Gtk.Image ();
		this.image2.Name = "image2";
		this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("EscuelaPrimaria.Imagenes.EscuelaPrimaria2.png");
		this.fixed1.Add (this.image2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.image2]));
		w2.X = 34;
		w2.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entrar = new global::Gtk.Button ();
		this.entrar.WidthRequest = 100;
		this.entrar.CanFocus = true;
		this.entrar.Name = "entrar";
		this.entrar.UseUnderline = true;
		this.entrar.Label = global::Mono.Unix.Catalog.GetString ("Entrar");
		this.fixed1.Add (this.entrar);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entrar]));
		w3.X = 241;
		w3.Y = 299;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.nombreTxt = new global::Gtk.Entry ();
		this.nombreTxt.CanFocus = true;
		this.nombreTxt.Name = "nombreTxt";
		this.nombreTxt.IsEditable = true;
		this.nombreTxt.InvisibleChar = '●';
		this.fixed1.Add (this.nombreTxt);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.nombreTxt]));
		w4.X = 98;
		w4.Y = 149;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Contraseña:");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w5.X = 46;
		w5.Y = 178;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Estatus:");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w6.X = 48;
		w6.Y = 230;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.selecTxt = global::Gtk.ComboBox.NewText ();
		this.selecTxt.AppendText (global::Mono.Unix.Catalog.GetString ("Estudiante"));
		this.selecTxt.AppendText (global::Mono.Unix.Catalog.GetString ("Maestro"));
		this.selecTxt.AppendText (global::Mono.Unix.Catalog.GetString ("Cordinacion"));
		this.selecTxt.WidthRequest = 156;
		this.selecTxt.Name = "selecTxt";
		this.selecTxt.Active = 0;
		this.fixed1.Add (this.selecTxt);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.selecTxt]));
		w7.X = 100;
		w7.Y = 250;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.contraTxt = new global::Gtk.Entry ();
		this.contraTxt.CanFocus = true;
		this.contraTxt.Name = "contraTxt";
		this.contraTxt.IsEditable = true;
		this.contraTxt.Visibility = false;
		this.contraTxt.InvisibleChar = '●';
		this.fixed1.Add (this.contraTxt);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.contraTxt]));
		w8.X = 97;
		w8.Y = 201;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 395;
		this.DefaultHeight = 367;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.entrar.Clicked += new global::System.EventHandler (this.OnEntrarClicked);
	}
}
